services:
  ospk_web_prod:
    build: .
    container_name: ospk_web_prod
    ports:
      - 22002:22002
      - 11001:11001
    volumes:
      - ./static:/srv/packages/frontend/dest
    command: npm run start -w @ospk/web-backend
